<?xml version="1.0"?>
<package format="2">
  <name>insta360_ros2_cuda_driver</name>
  <version>1.0.0</version>
  <description>Insta360 camera capture, H.264 decoding, and native CUDA stitching for ROS 2.</description>

  <maintainer email="asheshvasalya@gmail.com">Ashesh Vasalya</maintainer>
  <license>MIT</license>
  <license>Apache-2.0</license>

  <url type="repository">https://github.com/avasalya/insta360_ros2_cuda_driver</url>
  <url type="bugtracker">https://github.com/avasalya/insta360_ros2_cuda_driver/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>camera_info_manager</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>
  <depend>rcl_interfaces</depend>
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>

  <exec_depend>image_view</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
